# Generated by Django 4.2.7 on 2024-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_remove_product_catergory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(null=True, related_name='categories', to='product.product'),
        ),
    ]
