# Generated by Django 4.2.7 on 2024-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='product.product'),
        ),
    ]
